[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "omegabot-poligon77"
version = "2025.02"
dependencies = [
    "opencv-contrib-python>=4.11.0.86",
    "pymavlink>=2.4.42",
    "requests>=2.32.3"
]